-- Media Management System
-- Adds support for managing tour and schedule photos with metadata

-- Main media table
CREATE TABLE media (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- References (explicit FKs, not polymorphic)
    tour_id UUID REFERENCES tours(id) ON DELETE CASCADE,
    schedule_id UUID REFERENCES tour_schedules(id) ON DELETE CASCADE,

    -- S3 storage
    s3_key VARCHAR(512) UNIQUE NOT NULL,
    url VARCHAR(1024) NOT NULL,

    -- Multilingual metadata
    alt_translations JSONB DEFAULT '{"es": "", "en": "", "pt": ""}',
    caption_translations JSONB DEFAULT '{"es": "", "en": "", "pt": ""}',

    -- Tags for search and organization
    tags TEXT[] DEFAULT '{}',

    -- File information
    size_bytes BIGINT NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    original_filename VARCHAR(512),

    -- Image variants (thumbnail, medium, full) - populated by background job
    variants JSONB DEFAULT '{}',

    -- EXIF metadata (camera, GPS, settings)
    exif_data JSONB DEFAULT '{}',

    -- Timestamps
    uploaded_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    taken_at TIMESTAMPTZ,  -- Photo date from EXIF or manual entry

    -- Constraints: media can belong to tour, schedule, or be loose
    CONSTRAINT media_ref_check CHECK (
        (tour_id IS NOT NULL AND schedule_id IS NULL) OR
        (schedule_id IS NOT NULL) OR
        (tour_id IS NULL AND schedule_id IS NULL)
    )
);

-- Indexes for efficient queries
CREATE INDEX idx_media_owner ON media(owner_id);
CREATE INDEX idx_media_tour ON media(tour_id) WHERE tour_id IS NOT NULL;
CREATE INDEX idx_media_schedule ON media(schedule_id) WHERE schedule_id IS NOT NULL;
CREATE INDEX idx_media_tags ON media USING GIN(tags);
CREATE INDEX idx_media_taken_at ON media(taken_at) WHERE taken_at IS NOT NULL;
CREATE INDEX idx_media_uploaded_at ON media(uploaded_at DESC);

-- Join table for tour media with ordering
CREATE TABLE tour_media (
    tour_id UUID NOT NULL REFERENCES tours(id) ON DELETE CASCADE,
    media_id UUID NOT NULL REFERENCES media(id) ON DELETE CASCADE,
    display_order INT DEFAULT 0 NOT NULL,
    is_hero BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    PRIMARY KEY (tour_id, media_id)
);

-- Ensure only one hero image per tour
CREATE UNIQUE INDEX idx_tour_media_hero ON tour_media(tour_id) WHERE is_hero = TRUE;

-- Ensure unique display order per tour
CREATE UNIQUE INDEX idx_tour_media_order ON tour_media(tour_id, display_order);

-- Join table for schedule media with ordering
CREATE TABLE schedule_media (
    schedule_id UUID NOT NULL REFERENCES tour_schedules(id) ON DELETE CASCADE,
    media_id UUID NOT NULL REFERENCES media(id) ON DELETE CASCADE,
    display_order INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    PRIMARY KEY (schedule_id, media_id)
);

-- Ensure unique display order per schedule
CREATE UNIQUE INDEX idx_schedule_media_order ON schedule_media(schedule_id, display_order);

-- Comments for documentation
COMMENT ON TABLE media IS 'Stores all media files (photos) for tours, schedules, and loose media';
COMMENT ON COLUMN media.tour_id IS 'If set, this media belongs to a tour (but not assigned to gallery yet)';
COMMENT ON COLUMN media.schedule_id IS 'If set, this media belongs to a specific schedule instance';
COMMENT ON COLUMN media.variants IS 'JSON with thumbnail, medium, and full URLs generated by background job';
COMMENT ON COLUMN media.taken_at IS 'Date/time photo was taken (from EXIF or manual entry)';
COMMENT ON TABLE tour_media IS 'Junction table mapping media to tour galleries with ordering';
COMMENT ON TABLE schedule_media IS 'Junction table mapping media to schedule galleries with ordering';
